### ISSUE TITLE
Dealing with version mismatches

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/stamp#6]
this is nessecary for npm v2
only solution I see is adding a global 😞

**Comment by jimdebeer** [comment]
this may also cause confusion

**Comment by jimdebeer** [comment]
ok add a global -- its not good enough to just say do a install

**Comment by jimdebeer** [comment]
@boite I can add a version resolver -- it uses globals so a bit ugly

**Comment by boite** [comment]
@jimdebeer well that's all very interesting, but I think you mentioned the wrong person :smile:. Anyway, it was nice to meet you!

**Comment by jimdebeer** [comment]
ah sorry @boite I meant @boitewitte :D and likewise meeting you ;)

**Comment by jimdebeer** [comment]
this is nessecvary
